export const AUTHENTICATION_LOGIN_SUCCESS = "AUTHENTICATION_LOGIN_SUCCESS";
export const AUTHENTICATION_LOGIN_FAILURE = "AUTHENTICATION_LOGINFAILURE";
export const AUTHENTICATION_LOGIN_REQUESTED = "AUTHENTICATION_LOGIN_REQUESTED";
export const AUTHENTICATION_TOKEN_CHECK_REQUESTED =
  "AUTHENTICATION_TOKEN_CHECK_REQUESTED";
export const AUTHENTICATION_LOGOUT_REQUESTED =
  "AUTHENTICATION_LOGOUT_REQUESTED";
export const AUTHENTICATION_LOGOUT = "AUTHENTICATION_LOGOUT";
